Repository fusionjs/fusion-plugin-csrf-protection, pull requests merged in 2018-11, with the labels that each got.

#159 Release v2.0.0-0
  package.json
Labels: release

#161 Update dependencies and types for flow@0.85
  flow-typed/tape-cup_v4.x.x.js
  package.json
  src/browser.js
  src/server.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#163 Release v2.0.0
  package.json
Labels: release

#165 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
