Repository fusionjs/fusion-plugin-csrf-protection, pull requests merged in 2018-09, with the labels that each got.

#139 Upgrade dependencies and fix new flow error
  package.json
  src/browser.js
  yarn.lock
Labels: greenkeeping

#141 Release v1.0.6-1
  package.json
Labels: release

#144 Release v1.0.6
  package.json
Labels: release

#143 Fix flow 0.80.0 error in verifyExpiry
  src/shared.js
Labels: bugfix
